    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.sp.senac.d154.lojacalcados;

import br.sp.senac.d154.lojacalcados.models.CadasatroCliente;
import java.util.ArrayList;
import br.sp.senac.d154.lojacalcados.dao.ClienteDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lorena.eaprado
 */
public class TelaClientes extends javax.swing.JFrame {

    /**
     * Creates new form TelaClientes
     */
    public TelaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        tglAdicionar = new javax.swing.JToggleButton();
        tglExcluir = new javax.swing.JToggleButton();
        txtbuscarCli = new javax.swing.JTextField();
        tgleditar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("Clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBuscar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tbClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "Endereço", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbClientes);

        tglAdicionar.setBackground(new java.awt.Color(102, 255, 102));
        tglAdicionar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        tglAdicionar.setText("Adicionar");
        tglAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglAdicionarActionPerformed(evt);
            }
        });

        tglExcluir.setBackground(new java.awt.Color(255, 51, 51));
        tglExcluir.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        tglExcluir.setText("Excluir");
        tglExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglExcluirActionPerformed(evt);
            }
        });

        txtbuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarCliActionPerformed(evt);
            }
        });

        tgleditar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tgleditar.setText("Editar");
        tgleditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgleditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tglAdicionar)
                .addGap(18, 18, 18)
                .addComponent(tglExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgleditar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtbuscarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglAdicionar)
                    .addComponent(tglExcluir)
                    .addComponent(btnBuscar)
                    .addComponent(txtbuscarCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgleditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        if(txtbuscarCli.getText().trim().equals("")){
        recarregarTabela();
        }else{
            int numeroBuscar = Integer.parseInt(txtbuscarCli.getText());
           ArrayList<CadasatroCliente>listaRetorno = ClienteDAO.buscarPorNumero(numeroBuscar);
           DefaultTableModel modelo =(DefaultTableModel) tbClientes.getModel();
           for(CadasatroCliente item:listaRetorno){
               modelo.setRowCount(0);
               modelo.addRow(new String[]{
                           String.valueOf(item.getClienteID()),
                        String.valueOf(item.getNome()),
                        String.valueOf(item.getCpf()),
                        String.valueOf(item.getEndereco()),
                        String.valueOf(item.getTelefone())
               });
           }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    public void recarregarTabela(){
        
           ArrayList<CadasatroCliente> lista = ClienteDAO.listar();
      
        DefaultTableModel modelo =(DefaultTableModel) tbClientes.getModel();
        modelo.setRowCount(0);
        
        for (CadasatroCliente item : lista) {
            modelo.addRow(new String[]{
                        String.valueOf(item.getClienteID()),
                        String.valueOf(item.getNome()),
                        String.valueOf(item.getCpf()),
                        String.valueOf(item.getEndereco()),
                        String.valueOf(item.getTelefone())                       
            });
                
        }
    }
    private void tglExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglExcluirActionPerformed
        
        int linhaSelecionada = tbClientes.getSelectedRow();
        
        DefaultTableModel modelo = (DefaultTableModel) tbClientes.getModel();
     
         if (linhaSelecionada >= 0) {
        
        int ExcluirCliente = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());
        
        
     boolean retorno = ClienteDAO.Excluir(ExcluirCliente);
        if(retorno){
            JOptionPane.showMessageDialog(rootPane,"Excluido Com Sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Falha ao Excluir");
        } 
         
         }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha!");
        }
        
        
        recarregarTabela();
    }//GEN-LAST:event_tglExcluirActionPerformed

    private void tglAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglAdicionarActionPerformed
       TelaCadastroClientes add = new TelaCadastroClientes();
       add.setVisible(true);
        
    }//GEN-LAST:event_tglAdicionarActionPerformed

    private void txtbuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarCliActionPerformed
        
    }//GEN-LAST:event_txtbuscarCliActionPerformed

    private void tgleditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgleditarActionPerformed
        
     int linhaSelecionada = tbClientes.getSelectedRow();
        
        DefaultTableModel modelo = (DefaultTableModel)tbClientes.getModel();
       
        if (linhaSelecionada >= 0) {
        
        int IdSelecionado = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());    
        String nomeSelecionado =  modelo.getValueAt(linhaSelecionada, 1).toString(); 
        String cpfSelecionado =  modelo.getValueAt(linhaSelecionada, 2).toString();  
        String enderecoSelecionado =  modelo.getValueAt(linhaSelecionada, 3).toString(); 
        String telefoneSelecionado =  modelo.getValueAt(linhaSelecionada, 4).toString(); 
        
        CadasatroCliente objAlterar = new CadasatroCliente(IdSelecionado,nomeSelecionado,cpfSelecionado,enderecoSelecionado,telefoneSelecionado);
       
       TelaCadastroClientes alterar = new TelaCadastroClientes(objAlterar);
       alterar.setVisible(true);     
         }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha!");
        }
        
    }//GEN-LAST:event_tgleditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClientes;
    private javax.swing.JToggleButton tglAdicionar;
    private javax.swing.JToggleButton tglExcluir;
    private javax.swing.JToggleButton tgleditar;
    private javax.swing.JTextField txtbuscarCli;
    // End of variables declaration//GEN-END:variables
}
