/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.sp.senac.d154.lojacalcados;

import br.sp.senac.d154.lojacalcados.TelaCadastroProduto;
import br.sp.senac.d154.lojacalcados.dao.ProdutoDAO;
import br.sp.senac.d154.lojacalcados.models.CadasatroCliente;
import br.sp.senac.d154.lojacalcados.models.CadastroProduto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolas.smacedo
 */
public class TelaProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaProduto
     */
    public TelaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        lblProdutos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        btnAlterarProduto = new javax.swing.JButton();
        TxtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        tglbtnRemover = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblProdutos.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblProdutos.setText("Produtos Em Estoque");

        tbProdutos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigoP", "NomeProduto", "Modelo", "Cor ", "Tamanho ", "Qtde", "Preço"
            }
        ));
        jScrollPane1.setViewportView(tbProdutos);

        btnAlterarProduto.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnAlterarProduto.setText("Alterar Produto");
        btnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutoActionPerformed(evt);
            }
        });

        TxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tglbtnRemover.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tglbtnRemover.setText("Remover");
        tglbtnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglbtnRemoverActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jToggleButton1.setText("Adicionar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lblProdutos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlterarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tglbtnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarProduto)
                    .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(tglbtnRemover)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutoActionPerformed
         int linhaSelecionada = tbProdutos.getSelectedRow();
        
        DefaultTableModel modelo = (DefaultTableModel)tbProdutos.getModel();
         if (linhaSelecionada >= 0) {
        int IdProdutoSelecionado = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());    
        String nomePSelecionado =  modelo.getValueAt(linhaSelecionada, 1).toString(); 
        String ModeloSelecionado =  modelo.getValueAt(linhaSelecionada, 2).toString();  
        String corSelecionada =  modelo.getValueAt(linhaSelecionada, 3).toString(); 
        String tamanhoSelecionado =  modelo.getValueAt(linhaSelecionada, 4).toString(); 
        int quantidadeSelecionada = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 5).toString()); 
        double PrecoSelecionado = Double.parseDouble(modelo.getValueAt(linhaSelecionada, 6).toString()); 
        
        CadastroProduto objAlterar = new CadastroProduto(nomePSelecionado, ModeloSelecionado, tamanhoSelecionado, corSelecionada, quantidadeSelecionada,IdProdutoSelecionado ,PrecoSelecionado);
       
       TelaCadastroProduto alterar = new TelaCadastroProduto(objAlterar);
       alterar.setVisible(true);
         }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha!");
        }

    }//GEN-LAST:event_btnAlterarProdutoActionPerformed

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

         if(TxtBuscar.getText().trim().equals("")){
        recarregarTabela();
        }else{
            int numeroBuscar = Integer.parseInt(TxtBuscar.getText());
           ArrayList<CadastroProduto>listaRetorno = ProdutoDAO.buscarPorNumero(numeroBuscar);
           DefaultTableModel modelo =(DefaultTableModel) tbProdutos.getModel();
           for(CadastroProduto item:listaRetorno){
               modelo.setRowCount(0);
               modelo.addRow(new String[]{
                           String.valueOf(item.getCodigoP()),
                        String.valueOf(item.getNomeproduto()),
                        String.valueOf(item.getModelo()),
                        String.valueOf(item.getCor()),
                        String.valueOf(item.getTamanho()),
                        String.valueOf(item.getQuantidade()),
                        String.valueOf(item.getPreco()),
               });
           }
        }
                                             
    }//GEN-LAST:event_btnBuscarActionPerformed
public void recarregarTabela(){
        
           ArrayList<CadastroProduto> lista = ProdutoDAO.listar();
      
        DefaultTableModel modelo =(DefaultTableModel) tbProdutos.getModel();
        modelo.setRowCount(0);
        
        for (CadastroProduto item : lista) {
            modelo.addRow(new String[]{
                        String.valueOf(item.getCodigoP()),
                        String.valueOf(item.getNomeproduto()),
                        String.valueOf(item.getModelo()),
                        String.valueOf(item.getCor()),
                        String.valueOf(item.getTamanho()),
                        String.valueOf(item.getQuantidade()),
                        String.valueOf(item.getPreco()),                       
            }); 
                
        }
}
    private void tglbtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglbtnRemoverActionPerformed

      int linhaSelecionada = tbProdutos.getSelectedRow();
        
        DefaultTableModel modelo = (DefaultTableModel) tbProdutos.getModel();
        if (linhaSelecionada >= 0) {
     int ExcluirProduto = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());
        
        
     boolean retorno = ProdutoDAO.Excluir(ExcluirProduto);
        if(retorno){
            JOptionPane.showMessageDialog(rootPane,"Excluido Com Sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Falha ao Excluir");
        }
         }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha!");
        }
        recarregarTabela();

    }//GEN-LAST:event_tglbtnRemoverActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    TelaCadastroProduto add = new TelaCadastroProduto();
       add.setVisible(true);        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns 11".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JToggleButton tglbtnRemover;
    // End of variables declaration//GEN-END:variables
}
